apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  jwt-key: YXNkZg==
## this is another method of creating a secret in kubernetes. The other method will be to
## write an imperative command: kubctl create secret generic jwt-secret --from-literal-jwt=asdf where
## generic is the type of secret we are trying to create, jw-secret is the name of the secret
## jwt=asdf is the key/value. We'll be using the command base style and one reason I can think of why
## is that it's better the config file holding the jwt isn't shown especially when you push to a repo.
## obviosly, you can add this file to the .gitignore or it might not even matter since we can kinda encode the
## data we are trying to hide. Another reason we avoiding in using a config file is to prevent us from list the
## sign-in key of the jwt in the config file as we're doing above; we can reference a local environment variable that holds
## sign-in key inside this config file but using the imperative command is just way easier.

## how to encode some sensitive data you might want to save in a secret which is a prefered way
## echo -n 'sign-in key for jwt example asdf' | base64
